theme: jekyll-theme-minimal
github:
  is_project_page: false
title: The Future of Work(places)
description: a CSCW 2019 workshop on creating a sense of place for on-demand work
logo: assets/image/v2.jpg